import type { Producto } from "@/types";

/**
 * Datos de ejemplo para desarrollo local sin conexión a Redis/KV.
 */
export const MOCK_STOCK_PROV_1: Producto[] = [
    {
        id: "mock-001",
        marca: "Apple",
        modelo: "iPhone 15 Pro 128GB",
        categoria: "Smartphones",
        variantes: ["Black Titanium", "Natural Titanium", "Blue Titanium"],
        precio_usd: 950,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
    {
        id: "mock-002",
        marca: "Apple",
        modelo: "iPhone 15 Pro 256GB",
        categoria: "Smartphones",
        variantes: ["Black Titanium", "White Titanium"],
        precio_usd: 1050,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
    {
        id: "mock-003",
        marca: "Apple",
        modelo: "iPhone 14 128GB",
        categoria: "Smartphones",
        variantes: ["Midnight", "Starlight", "Blue", "Purple"],
        precio_usd: 580,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
    {
        id: "mock-004",
        marca: "Apple",
        modelo: "iPhone 13 128GB",
        categoria: "Smartphones",
        variantes: ["Midnight", "Pink"],
        precio_usd: 430,
        precio_ars: null,
        condicion: "CPO",
        proveedor: "prov_1",
    },
    {
        id: "mock-005",
        marca: "Samsung",
        modelo: "Galaxy S24 Ultra 256GB",
        categoria: "Smartphones",
        variantes: ["Titanium Black", "Titanium Gray", "Titanium Violet"],
        precio_usd: 920,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
    {
        id: "mock-006",
        marca: "Samsung",
        modelo: "Galaxy S24 128GB",
        categoria: "Smartphones",
        variantes: ["Onyx Black", "Marble Gray"],
        precio_usd: 600,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
    {
        id: "mock-007",
        marca: "Apple",
        modelo: "MacBook Air M2 13\" 256GB",
        categoria: "Computadoras MacBook Air y Pro",
        variantes: ["Space Gray", "Silver", "Midnight"],
        precio_usd: 850,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
    {
        id: "mock-008",
        marca: "Apple",
        modelo: "AirPods Pro 2da Gen USB-C",
        categoria: "Audio",
        variantes: [],
        precio_usd: 180,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_1",
    },
];

export const MOCK_STOCK_PROV_2: Producto[] = [
    {
        id: "mock-101",
        marca: "Samsung",
        modelo: "Galaxy Z Flip 5 256GB",
        categoria: "Smartphones",
        variantes: ["Graphite", "Lavender", "Cream"],
        precio_usd: 750,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-102",
        marca: "Google",
        modelo: "Pixel 8 Pro 128GB",
        categoria: "Smartphones",
        variantes: ["Obsidian", "Porcelain", "Bay"],
        precio_usd: 680,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-103",
        marca: "JBL",
        modelo: "Flip 7",
        categoria: "Audio",
        variantes: ["Black", "Blue", "Red", "Teal"],
        precio_usd: 85,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-104",
        marca: "Sony",
        modelo: "WH-1000XM5",
        categoria: "Audio",
        variantes: ["Black", "Silver"],
        precio_usd: 250,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-105",
        marca: "Apple",
        modelo: "iPad Air M1 64GB WiFi",
        categoria: "Tablets",
        variantes: ["Space Gray", "Starlight"],
        precio_usd: 420,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-106",
        marca: "Apple",
        modelo: "Apple Watch Series 9 45mm",
        categoria: "Smartwatches",
        variantes: ["Midnight", "Starlight", "Pink"],
        precio_usd: 320,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-107",
        marca: "Samsung",
        modelo: "Galaxy S23 FE 128GB",
        categoria: "Smartphones",
        variantes: ["Graphite", "Cream", "Mint"],
        precio_usd: 410,
        precio_ars: 540000,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
    {
        id: "mock-108",
        marca: "Apple",
        modelo: "iPhone 14 Pro 128GB",
        categoria: "Smartphones",
        variantes: ["Space Black", "Gold"],
        precio_usd: 650,
        precio_ars: null,
        condicion: "Usado",
        proveedor: "prov_2",
    },
    {
        id: "mock-109",
        marca: "Sony",
        modelo: "Alpha a7 IV",
        categoria: "Cámaras Fotográficas",
        variantes: ["Black"],
        precio_usd: 2400,
        precio_ars: null,
        condicion: "Nuevo",
        proveedor: "prov_2",
    },
];
